version: "2"
run:
  tests: true
linters:
  enable:
    - gocritic
    - misspell
    - prealloc
    - revive
    - staticcheck
    - unparam
  disable:
    - errcheck
  settings:
    gocritic:
      enabled-checks:
        - importShadow
        - nilValReturn
        - rangeValCopy
    revive:
      severity: warning
      rules:
        - name: exported
          severity: warning
          disabled: false
        - name: blank-imports
          disabled: false
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: true
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/piligrimm/tls
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
